

DATA = [
    # Chunk of text with citations,  List of citations
    (
        '''A search justified by consent must remain with the scope of the consent given. *State v. Ladd*, 246 N.C. App. 295, 299 (2016). "When an individual gives a general statement of consent without express limitations, the scope of a permissible search is not limitless. Rather it is constrained by the bounds of reasonableness. . . ." *North Carolina v. Johnson*, 177 N.C. App. 122, 125 2006 (cleaned up). The defining inquiry for determining the scope of a consent search is "what would the typical reasonable person have understood by the exchange between the officer and the suspect?" Florida v. Jimeno, 500 U.S. 248 at 251 (1991); *State v. Stone*, 362 N.C. 50, 53 (2007). Further, "[t]he scope of a search is generally defined by its expressed object." Should this Court conclude otherwise, Mr. Outlaw respectfully requests this Court to invoke Rule 2 to consider whether Kelly's search of Outlaw's car exceeded the scope of Outlaw's consent. NCR. Appellate Procedure Rule 2 ("To prevent manifest injustice to a party . . . [an appellate court] may . . . suspend or vary the requirements or provisions of any of [the] rules"). This has been our longstanding position. *Id*. Nor does Rule 2 alter this analysis. *See, State v. McDougald*, 181 N. C. App. 41, 49 (2007) (Elmore, J. dissenting) (opining that he would invoke Rule 2 to avoid manifest injustice and address the merits of a suppression issue not properly before the Court), *rev'd in part on grounds stated in dissent, and remanding for consideration on the merits*, 362 N.C. 224 (2008) (*per curiam*); *State v. Adams*, 250 N.C. App. at 674 (2016) (invoking Rule 2 to reach the merits of defendant's unpreserved motion-to-suppress argument); *State V. Brunson*, 165 N.C. App. 667, 670 (2004) (invoking Rule 2 to review the merits of a statutory argument on appeal where the defendant made only a constitutional argument below); *State v. Hall*, 134 N.C. App. 417, 424 1999 (invoking Rule 2 to reach the merits of an argument not raised below in the defendant's motion to suppress identification evidence). But we must consider arguments implicitly raised. Id. The decision below is reversed.''',
        '''[{"full_span": "*State v. Ladd*, 246 N.C. App. 295, 299 (2016).", "source_type": "case"}, {"full_span": "*North Carolina v. Johnson*, 177 N.C. App. 122, 125 2006 (cleaned up).", "source_type": "case"}, {"full_span": "Florida v. Jimeno, 500 U.S. 248 at 251 (1991);", "source_type": "case"}, {"full_span": "*State v. Stone*, 362 N.C. 50, 53 (2007).", "source_type": "case"}, {"full_span": "NCR. Appellate Procedure Rule 2 (\\"To prevent manifest injustice to a party . . . [an appellate court] may . . . suspend or vary the requirements or provisions of any of [the] rules\\").", "source_type": "rules"}, {"full_span": "*Id*.", "source_type": "id"}, {"full_span": "*See, State v. McDougald*, 181 N. C. App. 41, 49 (2007) (Elmore, J. dissenting) (opining that he would invoke Rule 2 to avoid manifest injustice and address the merits of a suppression issue not properly before the Court), *rev\'d in part on grounds stated in dissent, and remanding for consideration on the merits*, 362 N.C. 224 (2008) (*per curiam*);", "source_type": "case"}, {"full_span": "*State v. Adams*, 250 N.C. App. at 674 (2016) (invoking Rule 2 to reach the merits of defendant\'s unpreserved motion-to-suppress argument);", "source_type": "case"}, {"full_span": "*State V. Brunson*, 165 N.C. App. 667, 670 (2004) (invoking Rule 2 to review the merits of a statutory argument on appeal where the defendant made only a constitutional argument below);", "source_type": "case"}, {"full_span": "*State v. Hall*, 134 N.C. App. 417, 424 1999 (invoking Rule 2 to reach the merits of an argument not raised below in the defendant\'s motion to suppress identification evidence).", "source_type": "case"}, {"full_span": "Id.", "source_type": "id"}]''',
    ),
]
